### ISSUE TITLE
Uso do if no arquivo desconto.java

### ISSUE THREAD

**Issue by owozsh** [mstr-Wolf/java_demo#1]
Recomendo trocar os "if / else if" por um switch, economiza processamento ;)

**Comment by mstr-Wolf** [comment]
Mal hábito do Python, ainda sou iniciante em Java kaksk

**Comment by owozsh** [comment]
Relaxa, é so uma dica, tinha uma época que eu não conhecia e quando descobri gostei bastante. // python também tem switch :) use à vontade
